export const REFRESH_COORDINATES = 'REFRESH_COORDINATES';
export const CHANGE_CURRENT_TAB = 'CHANGE_CURRENT_TAB';
export const CHANGE_CITY = 'CHANGE_CITY';
export const CHANGE_COUNTRY = 'CHANGE_COUNTRY';
export const CHANGE_TODAY_WEATHER_INFO = 'CHANGE_TODAY_WEATHER_INFO';
export const CHANGE_CURRENT_TEMPERATURE = 'CHANGE_CURRENT_TEMPERATURE';
export const CHANGE_TOMORROW_WEATHER = 'CHANGE_CURRENT_DAY_WEATHER';
export const CHANGE_WEEK_WEATHER = 'CHANGE_WEEK_WEATHER';
